//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppPWA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceTiming.Mobile.PWA.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear current race data.
        /// </summary>
        public static string About_Bt_ClearRace {
            get {
                return ResourceManager.GetString("About_Bt_ClearRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current race data to Clipboard.
        /// </summary>
        public static string About_Bt_CopyToJson {
            get {
                return ResourceManager.GetString("About_Bt_CopyToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string About_Bt_TestCon {
            get {
                return ResourceManager.GetString("About_Bt_TestCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update current race with clipboard data.
        /// </summary>
        public static string About_Bt_UpdateFromJson {
            get {
                return ResourceManager.GetString("About_Bt_UpdateFromJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing race date !.
        /// </summary>
        public static string About_Err_CastJsonToRace {
            get {
                return ResourceManager.GetString("About_Err_CastJsonToRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version :.
        /// </summary>
        public static string About_Label_AppVersion {
            get {
                return ResourceManager.GetString("About_Label_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        public static string About_Label_Lang {
            get {
                return ResourceManager.GetString("About_Label_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Id :.
        /// </summary>
        public static string About_Label_UniqueId {
            get {
                return ResourceManager.GetString("About_Label_UniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion {0} KO.
        /// </summary>
        public static string About_Text_ConKo {
            get {
                return ResourceManager.GetString("About_Text_ConKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion {0} OK.
        /// </summary>
        public static string About_Text_ConOk {
            get {
                return ResourceManager.GetString("About_Text_ConOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current race data copied to clipboard.
        /// </summary>
        public static string About_Text_CopiedToClipboard {
            get {
                return ResourceManager.GetString("About_Text_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race &apos;{0}&apos; cleared.
        /// </summary>
        public static string About_Text_DataCleared {
            get {
                return ResourceManager.GetString("About_Text_DataCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear all results and participants ?.
        /// </summary>
        public static string About_Text_SureClearData {
            get {
                return ResourceManager.GetString("About_Text_SureClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR²Timing code.
        /// </summary>
        public static string CreateRace_Lbl_Ar2tCode {
            get {
                return ResourceManager.GetString("CreateRace_Lbl_Ar2tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string CreateRace_Lbl_Date {
            get {
                return ResourceManager.GetString("CreateRace_Lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateRace_Lbl_Name {
            get {
                return ResourceManager.GetString("CreateRace_Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEV server.
        /// </summary>
        public static string CreateRace_Lbl_Server {
            get {
                return ResourceManager.GetString("CreateRace_Lbl_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CreateRace_Lbl_Type {
            get {
                return ResourceManager.GetString("CreateRace_Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New race saved.
        /// </summary>
        public static string CreateRace_Txt_CreationDone {
            get {
                return ResourceManager.GetString("CreateRace_Txt_CreationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;{0}&apos; !.
        /// </summary>
        public static string Gen_Err_MissingField {
            get {
                return ResourceManager.GetString("Gen_Err_MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current race !.
        /// </summary>
        public static string Gen_Err_NoCurrentRace {
            get {
                return ResourceManager.GetString("Gen_Err_NoCurrentRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No participant !.
        /// </summary>
        public static string Gen_Err_NoParticipant {
            get {
                return ResourceManager.GetString("Gen_Err_NoParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Gen_Loading {
            get {
                return ResourceManager.GetString("Gen_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Gen_No {
            get {
                return ResourceManager.GetString("Gen_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet !.
        /// </summary>
        public static string Gen_NotImplemented {
            get {
                return ResourceManager.GetString("Gen_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sent.
        /// </summary>
        public static string Gen_NotSent {
            get {
                return ResourceManager.GetString("Gen_NotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string Gen_NotStarted {
            get {
                return ResourceManager.GetString("Gen_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Gen_Save {
            get {
                return ResourceManager.GetString("Gen_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at {0}.
        /// </summary>
        public static string Gen_StartedAt {
            get {
                return ResourceManager.GetString("Gen_StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Gen_Validate {
            get {
                return ResourceManager.GetString("Gen_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Gen_Yes {
            get {
                return ResourceManager.GetString("Gen_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see all results, go to.
        /// </summary>
        public static string Home_TextGoToAR2Timing {
            get {
                return ResourceManager.GetString("Home_TextGoToAR2Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to mobile app of AR²Timing..
        /// </summary>
        public static string Home_TextWelcome {
            get {
                return ResourceManager.GetString("Home_TextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new race.
        /// </summary>
        public static string Menu_CreateRace {
            get {
                return ResourceManager.GetString("Menu_CreateRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current race :.
        /// </summary>
        public static string Menu_Lbl_CurrentRace {
            get {
                return ResourceManager.GetString("Menu_Lbl_CurrentRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Menu_Participants {
            get {
                return ResourceManager.GetString("Menu_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passings.
        /// </summary>
        public static string Menu_Passings {
            get {
                return ResourceManager.GetString("Menu_Passings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string Menu_Races {
            get {
                return ResourceManager.GetString("Menu_Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Scratch.
        /// </summary>
        public static string Menu_RankingScratch {
            get {
                return ResourceManager.GetString("Menu_RankingScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start race.
        /// </summary>
        public static string Menu_StartRace {
            get {
                return ResourceManager.GetString("Menu_StartRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing.
        /// </summary>
        public static string Menu_Timing {
            get {
                return ResourceManager.GetString("Menu_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing Overview.
        /// </summary>
        public static string Menu_TimingOverview {
            get {
                return ResourceManager.GetString("Menu_TimingOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add participant.
        /// </summary>
        public static string Participants_Bt_AddPart {
            get {
                return ResourceManager.GetString("Participants_Bt_AddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import participants.
        /// </summary>
        public static string Participants_Bt_Import {
            get {
                return ResourceManager.GetString("Participants_Bt_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        public static string Participants_Bt_ImportBusy {
            get {
                return ResourceManager.GetString("Participants_Bt_ImportBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No participant found !.
        /// </summary>
        public static string Participants_Err_NoParticiant {
            get {
                return ResourceManager.GetString("Participants_Err_NoParticiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} participants imported.
        /// </summary>
        public static string Participants_Text_NbImported {
            get {
                return ResourceManager.GetString("Participants_Text_NbImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add below.
        /// </summary>
        public static string Passings_Bt_AddAfter {
            get {
                return ResourceManager.GetString("Passings_Bt_AddAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add above.
        /// </summary>
        public static string Passings_Bt_AddBefore {
            get {
                return ResourceManager.GetString("Passings_Bt_AddBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bib.
        /// </summary>
        public static string Passings_Bt_EditBib {
            get {
                return ResourceManager.GetString("Passings_Bt_EditBib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit time.
        /// </summary>
        public static string Passings_Bt_EditTime {
            get {
                return ResourceManager.GetString("Passings_Bt_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send passings.
        /// </summary>
        public static string Passings_Bt_Send {
            get {
                return ResourceManager.GetString("Passings_Bt_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string Passings_Bt_SendBusy {
            get {
                return ResourceManager.GetString("Passings_Bt_SendBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No passing to send !.
        /// </summary>
        public static string Passings_Err_NoPassing {
            get {
                return ResourceManager.GetString("Passings_Err_NoPassing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This passing is already removed !.
        /// </summary>
        public static string Passings_Err_PassAlreadyRemoved {
            get {
                return ResourceManager.GetString("Passings_Err_PassAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This passing is not removed !.
        /// </summary>
        public static string Passings_Err_PassNotRemoved {
            get {
                return ResourceManager.GetString("Passings_Err_PassNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter time.
        /// </summary>
        public static string Passings_Lbl_EnterTime {
            get {
                return ResourceManager.GetString("Passings_Lbl_EnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} passings sent.
        /// </summary>
        public static string Passings_Text_NbSent {
            get {
                return ResourceManager.GetString("Passings_Text_NbSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing added for bib  {0}.
        /// </summary>
        public static string Passings_Txt_PassingAdded {
            get {
                return ResourceManager.GetString("Passings_Txt_PassingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time changed to {0}.
        /// </summary>
        public static string Passings_Txt_TimeChanged {
            get {
                return ResourceManager.GetString("Passings_Txt_TimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a race.
        /// </summary>
        public static string Races_Bt_ImportRaces {
            get {
                return ResourceManager.GetString("Races_Bt_ImportRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb participants :.
        /// </summary>
        public static string Races_Lbl_NbParticipants {
            get {
                return ResourceManager.GetString("Races_Lbl_NbParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb passings :.
        /// </summary>
        public static string Races_Lbl_NbPassings {
            get {
                return ResourceManager.GetString("Races_Lbl_NbPassings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race &apos;{0}&apos; selected.
        /// </summary>
        public static string Races_Text_RaceSelected {
            get {
                return ResourceManager.GetString("Races_Text_RaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate ranking.
        /// </summary>
        public static string RankingScratch_Bt_CalculateRanking {
            get {
                return ResourceManager.GetString("RankingScratch_Bt_CalculateRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib.
        /// </summary>
        public static string RankingScratch_Lbl_Bib {
            get {
                return ResourceManager.GetString("RankingScratch_Lbl_Bib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laps.
        /// </summary>
        public static string RankingScratch_Lbl_Laps {
            get {
                return ResourceManager.GetString("RankingScratch_Lbl_Laps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RankingScratch_Lbl_Name {
            get {
                return ResourceManager.GetString("RankingScratch_Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb ranked :.
        /// </summary>
        public static string RankingScratch_Lbl_NbRanked {
            get {
                return ResourceManager.GetString("RankingScratch_Lbl_NbRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string RankingScratch_Lbl_Rank {
            get {
                return ResourceManager.GetString("RankingScratch_Lbl_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string RankingScratch_Lbl_Time {
            get {
                return ResourceManager.GetString("RankingScratch_Lbl_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string StartRace_Bt_Change {
            get {
                return ResourceManager.GetString("StartRace_Bt_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string StartRace_Bt_Reset {
            get {
                return ResourceManager.GetString("StartRace_Bt_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send start time.
        /// </summary>
        public static string StartRace_Bt_SendTime {
            get {
                return ResourceManager.GetString("StartRace_Bt_SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string StartRace_Bt_SendTimeBusy {
            get {
                return ResourceManager.GetString("StartRace_Bt_SendTimeBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartRace_Bt_Start {
            get {
                return ResourceManager.GetString("StartRace_Bt_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times already sent !.
        /// </summary>
        public static string StartRace_Err_AlreadySent {
            get {
                return ResourceManager.GetString("StartRace_Err_AlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race already started !.
        /// </summary>
        public static string StartRace_Err_AlreadyStarted {
            get {
                return ResourceManager.GetString("StartRace_Err_AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race have already passings !.
        /// </summary>
        public static string StartRace_Err_HavePassings {
            get {
                return ResourceManager.GetString("StartRace_Err_HavePassings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race not started yet !.
        /// </summary>
        public static string StartRace_Err_NotStarted {
            get {
                return ResourceManager.GetString("StartRace_Err_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib from :.
        /// </summary>
        public static string StartRace_Lbl_BibFrom {
            get {
                return ResourceManager.GetString("StartRace_Lbl_BibFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib range only.
        /// </summary>
        public static string StartRace_Lbl_BibRangeOnly {
            get {
                return ResourceManager.GetString("StartRace_Lbl_BibRangeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib to :.
        /// </summary>
        public static string StartRace_Lbl_BibTo {
            get {
                return ResourceManager.GetString("StartRace_Lbl_BibTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time :.
        /// </summary>
        public static string StartRace_Lbl_StartTime {
            get {
                return ResourceManager.GetString("StartRace_Lbl_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times sent :.
        /// </summary>
        public static string StartRace_Lbl_TimeSent {
            get {
                return ResourceManager.GetString("StartRace_Lbl_TimeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time already sent, are you sure to reset it ?.
        /// </summary>
        public static string StartRace_Txt_ConfirmReset {
            get {
                return ResourceManager.GetString("StartRace_Txt_ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race started.
        /// </summary>
        public static string StartRace_Txt_RacceStarted {
            get {
                return ResourceManager.GetString("StartRace_Txt_RacceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time sent.
        /// </summary>
        public static string StartRace_Txt_StartTimeReseted {
            get {
                return ResourceManager.GetString("StartRace_Txt_StartTimeReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time resets.
        /// </summary>
        public static string StartRace_Txt_StartTimeSent {
            get {
                return ResourceManager.GetString("StartRace_Txt_StartTimeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time changed.
        /// </summary>
        public static string StartRace_Txt_TimeChanged {
            get {
                return ResourceManager.GetString("StartRace_Txt_TimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide passed.
        /// </summary>
        public static string Timing_Bt_HidePassed {
            get {
                return ResourceManager.GetString("Timing_Bt_HidePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Timing_Bt_Mode {
            get {
                return ResourceManager.GetString("Timing_Bt_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show passed.
        /// </summary>
        public static string Timing_Bt_ShowPassed {
            get {
                return ResourceManager.GetString("Timing_Bt_ShowPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib :.
        /// </summary>
        public static string Timing_Lbl_Bib {
            get {
                return ResourceManager.GetString("Timing_Lbl_Bib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib....
        /// </summary>
        public static string Timing_Lbl_BibPlaceholder {
            get {
                return ResourceManager.GetString("Timing_Lbl_BibPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter bib.
        /// </summary>
        public static string Timing_Lbl_EnterBib {
            get {
                return ResourceManager.GetString("Timing_Lbl_EnterBib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race time :.
        /// </summary>
        public static string Timing_Lbl_RaceTime {
            get {
                return ResourceManager.GetString("Timing_Lbl_RaceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib changed to {0}.
        /// </summary>
        public static string Timing_Txt_BibChanged {
            get {
                return ResourceManager.GetString("Timing_Txt_BibChanged", resourceCulture);
            }
        }
    }
}
